apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod # letsencrypt 인증서의 이름
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: clearrworld@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: inong-com-tls
spec:
  secretName: inong-com-tls
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: api.inong.shop
  dnsNames:
<<<<<<< HEAD
  - api.inong.shop
=======
  - api.inong.store
>>>>>>> f933c52320397e07e033239327468bb3bbbc7450
