apiVersion: v1
kind: Service
metadata:
  name: openvidu-dev-service
  labels:
    app: openvidu-dev
spec:
  selector:
    app: openvidu-dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4443
  type: NodePort
