apiVersion: v1

kind: Service
metadata:
  name: product-service

spec:
  # ingress를 적용하기 위해 ClusterIP로 변경
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080 # pod 포트
  # depl의 labels와 맞아야 함 ⭐
  selector:
    app: product