server:
  port: 8080
spring:
  config:
    activate:
      on-profile: prod
#    import: application-secret.properties
  application:
    name: product-service
  datasource:
    url: jdbc:mariadb://${PRODUCT_PROD_DATABASE_ENDPOINT}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${PROD_DATABASE_MASTER_NAME}
    password: ${PROD_DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    tomcat.initial-size: 3  # 적절한 수치로 조정

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    defer-datasource-initialization: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+9
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: product-group
      group-instance-id: ${HOSTNAME}-instance
      auto-offset-reset: earliest
  data:
    redis:
      port: 6379
      host: ${REDIS_HOST}
    elasticsearch:
      uris: ${SPRING_ELASTICSEARCH_URIS}
      username: ${SPRING_ELASTICSEARCH_USERNAME}
      password: ${SPRING_ELASTICSEARCH_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: dongsanginong@gmail.com
    password: ${LOCAL_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
      auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: info

jwt:
  secret_key: ${JWT_SECRET_KEY}
  token:
    access_expiration_time: ${JWT_TOKEN_ACCESS_EXPIRATION_TIME}
    refresh_expiration_time: ${JWT_TOKEN_REFRESH_EXPIRATION_TIME}
fcm:
  secret-file: ${FCM_SECRET_FILE}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ${AWS_REGION}
      auto: false
    stack:
      auto: false
