server:
  port: 0
spring:
  config:
    activate:
      on-profile: prod
    import: application-secret.properties
  application:
    name: product-service
  datasource:
    url: ${PRODUCT_PROD_DATABASE_ENDPOINT}
    username: ${PROD_DATABASE_MASTER_NAME}
    password: ${PROD_DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    tomcat.initial-size: 3  # 적절한 수치로 조정

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    defer-datasource-initialization: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+9
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: product-group
      auto-offset-reset: earliest
  data:
    redis:
      port: 6379
      host: 127.0.0.1
    elasticsearch:
      uris: ${SPRING_ELASTICSEARCH_URIS}
      username: ${SPRING_ELASTICSEARCH_USERNAME}
      password: ${SPRING_ELASTICSEARCH_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: dongsanginong@gmail.com
    password: ${LOCAL_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
      auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: info


fcm:
  secret-file: ${FCM_SECRET_FILE}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ${AWS_REGION}
      auto: false
    stack:
      auto: false

