apiVersion: apps/v1

kind: Deployment
metadata:
  name: live-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: live

  template:
    metadata:
      labels:
        app: live
    spec:
      containers:
        - name: live
          # aws의 ecr 주소 사용
          image: 676206947506.dkr.ecr.ap-northeast-2.amazonaws.com/inong/live:latest
          ports:
            - containerPort: 8080
          resources:
            # 최대 할당가능량
            limits:
              cpu: "0.5"
              memory: "300Mi"
            # 최소 할당량
            requests:
              cpu: "250m"
              memory: "150Mi"
          env:
            - name: LIVE_PROD_DATABASE_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: LIVE_PROD_DATABASE_ENDPOINT
                  name: inong-app-secrets
            - name: PROD_DATABASE_MASTER_NAME
              valueFrom:
                secretKeyRef:
                  key: PROD_DATABASE_MASTER_NAME
                  name: inong-app-secrets
            - name: PROD_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PROD_DATABASE_PASSWORD
                  name: inong-app-secrets
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET_KEY
                  name: inong-app-secrets
            - name: JWT_TOKEN_ACCESS_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  key: JWT_TOKEN_ACCESS_EXPIRATION_TIME
                  name: inong-app-secrets
            - name: JWT_TOKEN_REFRESH_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  key: JWT_TOKEN_REFRESH_EXPIRATION_TIME
                  name: inong-app-secrets
            - name: OPENVIDU_URL
              valueFrom:
                secretKeyRef:
                  key: OPENVIDU_URL
                  name: inong-app-secrets
            - name: OPENVIDU_SECRET
              valueFrom:
                secretKeyRef:
                  key: OPENVIDU_SECRET
                  name: inong-app-secrets
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  key: KAFKA_BOOTSTRAP_SERVERS
                  name: inong-app-secrets
          #무중단 배포를 위한 컨테이너 헬스체크
          readinessProbe:
            httpGet:
              path: /live/healthcheck
              port: 8080
            # 컨테이너 시작 후 지연 시간 설정
            initialDelaySeconds: 10
            # 확인 반복 주기
            periodSeconds: 10
            # 요청 타임아웃 설정
            timeoutSeconds: 1 # 1초 이내에 안오면 실패로 간주
            # 성공 인식 횟수 설정. 몇번을 성공해야 성공으로 간주할거냐
            successThreshold: 1
            # 연속 실패 횟수: 연속적으로 5번을 실패하면 건강하지 않은 상태로 판단하여 기존 서버 종료시키지 않음
            failureThreshold: 5