apiVersion: apps/v1

kind: Deployment
metadata:
  name: apigateway-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway

  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          # aws의 ecr 주소 사용
          image: 676206947506.dkr.ecr.ap-northeast-2.amazonaws.com/inong/apigateway:latest
          ports:
            - containerPort: 8080
          resources:
            # 최대 할당가능량
            limits:
              cpu: "1"
              memory: "500Mi"
            # 최소 할당량
            requests:
              cpu: "0.5"
              memory: "250Mi"
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET_KEY
                  name: inong-app-secrets
            - name: JWT_TOKEN_ACCESS_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  key: JWT_TOKEN_ACCESS_EXPIRATION_TIME
                  name: inong-app-secrets
            - name: JWT_TOKEN_REFRESH_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  key: JWT_TOKEN_REFRESH_EXPIRATION_TIME
                  name: inong-app-secrets