server:
  port: 0

spring:
  config:
    activate:
      on-profile: prod
    import: application-secret.properties
  application:
    name: order-service
  datasource:
    url: ${ORDER_PROD_DB_ENDPOINT}
    username: ${PROD_DATABASE_MASTER_NAME}
    password: ${PROD_DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    defer-datasource-initialization: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+9
  sql:
    init:
      mode: always
  data:
    redis:
      port: 6379
      host: 127.0.0.1

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-group
      auto-offset-reset: earliest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: info


portone:
  api-secret: ${PORTONE_KAKAO_API_SECRET}
  payment-prefix: ${PORTONE_PAYMENT_PREFIX}
  store-id: ${PORTONE_STORE_ID}
  channel-key: ${PORTONE_CHANNELKEY}