server:
  port: 0

spring:
  config:
    activate:
      on-profile: dev
    import: application-secret.properties
  application:
    name: order-service
  datasource:
    url: jdbc:mariadb://${DEV_DATABASE_ENDPOINT}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DEV_DATABASE_MASTER_NAME}
    password: ${DEV_DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    defer-datasource-initialization: true
    tomcat.initial-size: 3  # 적절한 수치로 조정
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+9
  sql:
    init:
      mode: always

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-group
      auto-offset-reset: earliest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: info


portone:
  api-secret: ${PORTONE_KAKAO_API_SECRET}
  payment-prefix: ${PORTONE_PAYMENT_PREFIX}
  store-id: ${PORTONE_STORE_ID}
  channel-key: ${PORTONE_CHANNELKEY}