server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod
#    import: application-secret.properties
  application:
    name: order-service
  datasource:
    url: jdbc:mariadb://${ORDER_PROD_DATABASE_ENDPOINT}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${PROD_DATABASE_MASTER_NAME}
    password: ${PROD_DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    defer-datasource-initialization: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+9
  sql:
    init:
      mode: always
  data:
    redis:
      port: 6379
      host: ${REDIS_HOST}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: order-group
      group-instance-id: ${HOSTNAME}-instance
      auto-offset-reset: earliest

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: info


portone:
  api-secret: ${PORTONE_KAKAO_API_SECRET}
  payment-prefix: ${PORTONE_PAYMENT_PREFIX}
  store-id: ${PORTONE_STORE_ID}
  channel-key: ${PORTONE_CHANNELKEY}
